# Generated by Django 2.2.24 on 2022-04-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wportal', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
