# Generated by Django 2.2.24 on 2022-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wportal', '0006_auto_20220409_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='standard',
            field=models.CharField(choices=[('Select', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('Select', 'Select'), ('Tamil', 'Tamil'), ('English', 'English'), ('Maths', 'Maths'), ('Science', 'Science'), ('Social Science', 'Social Science')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(choices=[('Select', 'Select'), ('QuestionPaper', 'QuestionPaper'), ('Notes', 'Notes'), ('TextBook', 'TextBook'), ('StudyMaterial', 'StudyMaterial')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='unit',
            field=models.CharField(choices=[('Select', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=100),
        ),
    ]
